name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U setuptools wheel build twine

    - name: Build package
      run: |
        rm -rf ./build ./dist
        python -m build .

    - name: Upload to PyPI
      if: success()
      env:
        TWINE_USERNAME: __token__
        # You'll need to add this secret in your GitHub repository settings
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: python -m twine upload --skip-existing dist/*