name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install -e .

    - name: Run tests
      env:
        HYPHA_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        HYPHA_WORKSPACE: ${{ secrets.PERSONAL_WORKSPACE }}
      run: pytest -v